#ifndef __PREPROCESSOR_H__
#define __PREPROCESSOR_H__

#define PREPROC_SIGN '#'

/* Preprocessor keywords */
enum ca_preproc_keywords {
	PREPROC_KWORD_DEFINE,
	PREPROC_KWORD_IF,
	PREPROC_KWORD_IFDEF,
	PREPROC_KWORD_IFNDEF,
	PREPROC_KWORD_DEFINED,
	PREPROC_KWORD_UNDEF,
	PREPROC_KWORD_INCLUDE,
}

#endif

